spring.application.name=chat-trade



# H2\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9\u8a2d\u5b9a
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# H2\u30b3\u30f3\u30bd\u30fc\u30eb\u6709\u52b9\u5316\uff08\u30d6\u30e9\u30a6\u30b6\u3067\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9\u78ba\u8a8d\u53ef\u80fd\uff09
# spring.h2.console.enabled=true

# JPA\u8a2d\u5b9a
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop



# chat-trade\u7528DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql:chat_trade
spring.datasource.username=student
spring.datasource.password=himitu
spring.jpa.show-sql=true
spring.sql.init.mode=always